# SITE CONFIGURATION
baseurl: ""
url: "http://gillespieproject.com"

# THEME-SPECIFIC CONFIGURATION
theme_settings:
  # Meta
  title: The Gillespie Project
  avatar: icons/favicon.png
  description: The personal blog of Erik and Chris Gillespie

  # Header and footer text
  header_text:
  header_text_feature_image: img/feature/wedding_jump.png
  footer_text: >
    Copyright &copy; 2017 Erik and Chris Gillespie.
    <br>Non-commercial re-use with attribution encouraged.
    <br>All other rights reserved.

  # Icons
  rss: false
  email_address: # Full email address, e.g. "sam@example.com"
  behance:
  bitbucket:
  dribbble:
  facebook:
  flickr:
  github:
  google_plus:
  instagram:
  linkedin:  # Full URL
  pinterest:
  reddit:
  soundcloud:
  stack_exchange:  # Full URL
  steam:
  tumblr:
  twitter:
  wordpress:
  youtube:

  # Scripts
  google_analytics: "UA-62275452-1"
  disqus_shortname:
  muut_community_name: # From muut.com settings, e.g. "muttcommunityname"
  katex: false # Enable if using math markup

  # Localization strings
  str_follow_on: "Follow on"
  str_rss_follow: "Follow RSS feed"
  str_email: "Email"
  str_next: "Next"
  str_prev: "Prev"
  str_continue_reading: "Continue reading"

  # Colours, typography and padding
  # Open the "_sass > base" folder, and open "_variables.scss"
  google_fonts: "Source+Sans+Pro:400,700,700italic,400italic"

  # Post navigation
  post_navigation: false

# PAGINATION
paginate: 5
paginate_path: "blog/page:num"

# BUILD SETTINGS
markdown: kramdown
highlighter: rouge
sass:
  sass_dir: _sass
  style: :compressed
gems: [jekyll-paginate]
