# SITE CONFIGURATION
baseurl: ""
url: "http://gillespieproject.com"

# THEME-SPECIFIC CONFIGURATION
theme:
  # Meta
  title: The Gillespie Project
  logo:
  # used by search engines
  description: The personal blog of Erik and Chris Gillespie

  # Header and footer text
  header_text: >
     <p>Welcome to the online journal of Erik and Chris Gillespie!</p>

     <p>Here you'll find family updates and fun projects that are definitely safe to try at home.</p>
  header_text_feature_image:
  footer_text: >
    Copyright &copy; 2015 Erik and Chris Gillespie. Non-commercial re-use with attribution encouraged. All other rights reserved.

  # Scripts
  google_analytics: "UA-62275452-1"
  disqus_shortname:
  katex: false

  # Localization strings
  str_follow_on: "Follow on"
  str_rss_follow: "Follow RSS feed"
  str_email: "Email"
  str_next: "Next"
  str_prev: "Prev"
  str_continue_reading: "Continue reading"

  # Colours, typography and padding
  # Open the "_sass > base" folder, and open "_variables.scss"

social:
  erik:
    name: Erik
    # Icons
    email_address: erik.gillespie@gmail.com
    behance:
    bitbucket:
    dribbble:
    facebook:
    flickr:
    github: egillespie
    google_plus: +ErikGillespie
    gravatar_hash: 77e0d1571ed8fd1f9249a01e7569db05
    instagram:
    linkedin: https://www.linkedin.com/in/eriklgillespie
    pinterest:
    reddit: elgillespie
    soundcloud:
    stack_exchange: http://stackoverflow.com/users/1696044/erik-gillespie
    steam: 76561198029980002
    tumblr:
    twitter: eriklgillespie
    wordpress:
    youtube:
  chris:
    name: Chris
    # Icons
    email_address: chris.ann.gillespie@gmail.com
    behance:
    bitbucket:
    dribbble:
    facebook:
    flickr:
    github:
    google_plus: 110931175351252672881
    gravatar_hash: b67eed77f3245ea8c6023dfd6ae3cec2
    instagram:
    linkedin: https://www.linkedin.com/pub/chris-barott/12/9b0/343
    pinterest:
    reddit:
    soundcloud:
    stack_exchange:
    steam: 76561198014833542
    tumblr:
    twitter: reddragn
    wordpress:
    youtube:

# PAGINATION
paginate: 5
paginate_path: "blog/page:num"

# BUILD SETTINGS
markdown: kramdown
highlighter: pygments
sass:
  sass_dir: _sass
  style: :compressed
